@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

class BeneficiarioDTO {
  - razonSocial: String
  - direccion: String
  - id: String
  + equals(Object): boolean
  # canEqual(Object): boolean
  + hashCode(): int
  + getId(): String
  + getRazonSocial(): String
  + getDireccion(): String
}
entity CallbackPlanificacionRequest << record >> {
  - entregasPorPatente: Map<String, List<String>>
  - entregasSinAsignar: List<String>
  - fecha: String
  + fecha(): String
  + entregasPorPatente(): Map<String, List<String>>
  + entregasSinAsignar(): List<String>
}
class Camion {
  - capacidadVolumen: float
  - altura: float
  - coordenadas: List<Coordenada>
  - patente: String
  - capacidadCarga: float
  - gps: Gps
  + getPatente(): String
  + agregarGps(Gps): void
  + getAltura(): float
  + agregarCoordenada(Coordenada): void
  + getCapacidadVolumen(): float
  + getUbicacionActual(): Coordenada
  + actualizarDatos(float, float, float): void
  + posee(String): Boolean
  + getCapacidadCarga(): float
}
class CamionController {
  - service: CamionService
  + listar(Context): void
  + obtener(Context): void
  + crear(Context): void
  + eliminar(Context): void
  + actualizar(Context): void
}
class CamionMapper {
  - validarPositivo(Float, String): void
  + aDominio(CamionRequest): Camion
  + actualizarDominio(Camion, CamionRequest): void
  + aResponse(Camion): CamionResponse
  - validarCapacidades(CamionRequest): void
}
class CamionRepository {
  - INSTANCE: CamionRepository
  - camionesStore: Map<String, Camion>
  + buscarTodos(): List<Camion>
  + getInstancia(): CamionRepository
  + buscarCamionPorGps(String): Camion
  + guardar(Camion): void
  + buscarPorPatente(String): Optional<Camion>
  + eliminar(String): void
}
entity CamionRequest << record >> {
  - capacidadVolumen: Float
  - altura: Float
  - capacidadCarga: Float
  - patente: String
  + patente(): String
  + capacidadVolumen(): Float
  + capacidadCarga(): Float
  + altura(): Float
}
entity CamionResponse << record >> {
  - altura: float
  - capacidadCarga: float
  - capacidadVolumen: float
  - patente: String
  + capacidadCarga(): float
  + altura(): float
  + capacidadVolumen(): float
  + patente(): String
}
class CamionRoutes {
  + registrar(Javalin): void
}
class CamionService {
  - repository: CamionRepository
  + listar(): List<Camion>
  + eliminar(String): void
  + obtener(String): Camion
  + crear(CamionRequest): Camion
  + actualizar(String, CamionRequest): Camion
}
class Chofer {
  - nombre: String
  - licenciaConducir: String
  - apellido: String
  + getNombre(): String
  + getApellido(): String
  + getLicenciaConducir(): String
}
class Coordenada {
  - longitud: String
  - latitud: String
  + toString(): String
  + getLatitud(): String
  + getLongitud(): String
}
class DonacionAsignadaDTO {
  - beneficiario: BeneficiarioDTO
  - id: String
  - descripcion: String
  + getId(): String
  + getDescripcion(): String
  + getBeneficiario(): BeneficiarioDTO
}
entity DonacionRemotaResponse << record >>
class DonacionesClient {
  - ESTADO_ASIGNACION_REALIZADA: String
  - LISTA_DONACIONES_REMOTAS: Type
  - httpClient: HttpClient
  - baseUrl: String
  - gson: Gson
  + buscarDonacionesAsignadas(): List<DonacionAsignadaDTO>
  + cambiarEstadoDonacion(String, String): void
  - aDonacionAsignada(DonacionRemotaResponse): DonacionAsignadaDTO
  - enviar(HttpRequest, String): HttpResponse<String>
}
class DonacionesServiceConfig {
  + BASE_URL: String
}
class Entrega {
  - donaciones: List<DonacionAsignadaDTO>
  - camionAsignado: Camion
  - historialEstados: List<EstadoEntrega>
  - id: String
  - destino: BeneficiarioDTO
  - fotosRecepcion: List<String>
  + getHistorialEstados(): List<EstadoEntrega>
  + getEstadoActual(): TipoEstadoEntrega
  + marcarNoRecibida(String): void
  + reasignarCamion(Camion): void
  - cambiarEstado(TipoEstadoEntrega, String): void
  + getId(): String
  + getDonaciones(): List<DonacionAsignadaDTO>
  + iniciarTraslado(): void
  + getDestino(): BeneficiarioDTO
  + confirmarRecepcion(): void
  + setId(String): void
  + agregarFotoRecepcion(String): void
  + tieneFotos(): boolean
  + getFotosRecepcion(): List<String>
  + confirmarListaParaEntregar(): void
  + reingresarDeposito(): void
  + getCamionAsignado(): Camion
}
class EntregaController {
  - gestor: GestorEntrega
  + obtener(Context): void
  + reingresarADeposito(Context): void
  + listar(Context): void
  + marcarNoRecibida(Context): void
  + agregarFoto(Context): void
  + confirmarRecepcion(Context): void
  + setStado(Context): void
}
entity EntregaFotoRequest << record >> {
  - urlFoto: String
  + urlFoto(): String
}
class EntregaMapper {
  + aResponse(Entrega): EntregaResponse
  - aEstadoDto(EstadoEntrega): EstadoEntregaDto
}
entity EntregaNoRecibidaRequest << record >> {
  - motivo: String
  + motivo(): String
}
class EntregaRepository {
  - INSTANCE: EntregaRepository
  - store: Map<String, Entrega>
  + buscarPorId(String): Entrega
  + guardar(Entrega): void
  + getInstancia(): EntregaRepository
  + buscarTodas(): List<Entrega>
}
entity EntregaResponse << record >> {
  - destinoRazonSocial: String
  - patenteCamion: String
  - estadoActual: String
  - fotos: List<String>
  - destinoDireccion: String
  - historial: List<EstadoEntregaDto>
  - id: String
  + estadoActual(): String
  + id(): String
  + patenteCamion(): String
  + fotos(): List<String>
  + historial(): List<EstadoEntregaDto>
  + destinoRazonSocial(): String
  + destinoDireccion(): String
}
class EstacionRecepcion {
  - client: MqttClient
  - clientId: String
  - conversor: ObjectMapper
  - repoCamiones: CamionRepository
  - repoGps: GpsRepository
  - brokerUrl: String
  + desconectar(): void
  + conectar(): void
  + suscribir(String): void
}
class EstadoEntrega {
  - detalle: String
  - camion: Camion
  - fecha: LocalDateTime
  - tipoEstado: TipoEstadoEntrega
  + getDetalle(): String
  + getFecha(): LocalDateTime
  + getCamion(): Camion
  + getTipoEstado(): TipoEstadoEntrega
}
entity EstadoEntregaDto << record >> {
  - fecha: LocalDateTime
  - detalle: String
  - estado: String
  - patenteCamion: String
  + patenteCamion(): String
  + estado(): String
  + fecha(): LocalDateTime
  + detalle(): String
}
class GestorEntrega {
  - donacionesClient: DonacionesClient
  - entregaRepository: EntregaRepository
  - ESTADO_ENTREGADA: String
  - ESTADO_EN_DEPOSITO: String
  - ESTADO_ENTREGA_FALLIDA: String
  + marcarNoRecibida(String, String): void
  + confirmarRecepcion(String): void
  - propagarEstadoDonaciones(Entrega, String): void
  + reingresarADeposito(String): void
  + listar(): List<Entrega>
  + obtener(String): Entrega
  + agregarFoto(String, String): void
}
class GestorRuta {
  - rutaRepository: RutaRepository
  - donacionesClient: DonacionesClient
  - camionRepository: CamionRepository
  - ESTADO_LISTA_PARA_ENTREGAR: String
  - ESTADO_EN_TRASLADO: String
  - entregaRepository: EntregaRepository
  + iniciarRecorrido(String): void
  + obtener(String): Ruta
  - propagarEstadoDonaciones(Entrega, String): void
  + planificarEntregasPendientes(): List<Entrega>
  + listar(): List<Ruta>
  + procesarCallback(CallbackPlanificacionRequest): List<Ruta>
  + asignarChofer(String, Chofer): void
}
class Gps {
  - funciona: Boolean
  - fecha: LocalDateTime
  - imei: String
  - nivelBateria: String
  + getImei(): String
  + getFecha(): LocalDateTime
  + getNivelBateria(): String
  + getFunciona(): Boolean
  + actualizarEstado(String): void
  + dejoFuncionar(): void
}
class GpsMensaje {
  - id: String
  - nivelBateria: String
  - latitud: String
  - longitud: String
  + getId(): String
  + getNivelBateria(): String
  + getLatitud(): String
  + getLongitud(): String
  + setId(String): void
  + setNivelBateria(String): void
  + setLatitud(String): void
  + setLongitud(String): void
}
class GpsPublicador {
  + main(String[]): void
  - existeArchivo(Path): Boolean
  - pasanSeg(Integer): void
}
class GpsRepository {
  - INSTANCE: GpsRepository
  - gpsList: List<Gps>
  + buscarPorId(String): Gps
  + guardar(Gps): void
  + buscarTodos(): List<Gps>
  + getInstancia(): GpsRepository
}
class LogisticaApp {
  + PUERTO: int
  + main(String[]): void
  + crearApp(): Javalin
}
class OrquestadorLogistica {
  - MAX_DONACIONES_POR_LOTE: int
  - donacionesAllevar: List<DonacionAsignadaDTO>
  - camionesDisponibles: List<Camion>
  + procesarResultadoPlanificacion(ResultadoPlanificacion, LocalDate): List<Ruta>
  + armarLotesEntrega(List<Entrega>): List<List<Entrega>>
  + armarEntregasPendientes(): List<Entrega>
}
class PruebaDonacionesClient {
  + main(String[]): void
}
class PruebaRecepcion {
  - pasanMin(Integer): void
  + main(String[]): void
}
class ResultadoPlanificacion {
  - entregasPorCamion: Map<Camion, List<Entrega>>
  - entregasSinAsignar: List<Entrega>
  + getEntregasPorCamion(): Map<Camion, List<Entrega>>
  + getEntregasSinAsignar(): List<Entrega>
}
class Ruta {
  - camion: Camion
  - id: String
  - fecha: LocalDate
  - iniciada: boolean
  - entregasOrdenadas: List<Entrega>
  - chofer: Chofer
  + iniciarRecorrido(): void
  + getEntregasOrdenadas(): List<Entrega>
  + asignarChofer(Chofer): void
  + getFecha(): LocalDate
  + isIniciada(): boolean
  + getCamion(): Camion
  + getChofer(): Chofer
  + getId(): String
  + setId(String): void
}
class RutaController {
  - gestor: GestorRuta
  + listar(Context): void
  + obtener(Context): void
  + planificar(Context): void
  + recibirCallback(Context): void
  + iniciarRecorrido(Context): void
  + asignarChofer(Context): void
}
class RutaMapper {
  + aResponse(Ruta): RutaResponse
}
class RutaRepository {
  - store: Map<String, Ruta>
  - INSTANCE: RutaRepository
  + buscarPorId(String): Ruta
  + buscarTodas(): List<Ruta>
  + eliminar(String): void
  + guardar(Ruta): void
  + getInstancia(): RutaRepository
}
entity RutaRequest << record >> {
  - patenteCamion: String
  - fecha: LocalDate
  + patenteCamion(): String
  + fecha(): LocalDate
}
entity RutaResponse << record >> {
  - patenteCamion: String
  - fecha: LocalDate
  - id: String
  - nombreChofer: String
  - iniciada: boolean
  - idsEntregas: List<String>
  + nombreChofer(): String
  + iniciada(): boolean
  + id(): String
  + patenteCamion(): String
  + idsEntregas(): List<String>
  + fecha(): LocalDate
}
class RutaRoutes {
  + registrar(Javalin, RutaController, EntregaController): void
}
enum TipoEstadoEntrega << enumeration >> {
  + PENDIENTE: 
  + EN_TRASLADO: 
  + NO_RECIBIDA: 
  + ENTREGADA: 
  + valueOf(String): TipoEstadoEntrega
  + values(): TipoEstadoEntrega[]
}

Camion                       "1" *-[#595959,plain]-> "coordenadas\n*" Coordenada                   
Camion                       "1" *-[#595959,plain]-> "gps\n1" Gps                          
CamionController             "1" *-[#595959,plain]-> "service\n1" CamionService                
CamionMapper                  -[#595959,dashed]->  Camion                       : "«create»"
CamionMapper                  -[#595959,dashed]->  CamionResponse               : "«create»"
CamionRepository             "1" *-[#595959,plain]-> "camionesStore\n*" Camion                       
CamionRoutes                  -[#595959,dashed]->  CamionController             : "«create»"
CamionRoutes                  -[#595959,dashed]->  CamionService                : "«create»"
CamionService                "1" *-[#595959,plain]-> "repository\n1" CamionRepository             
DonacionAsignadaDTO          "1" *-[#595959,plain]-> "beneficiario\n1" BeneficiarioDTO              
DonacionesClient              -[#595959,dashed]->  BeneficiarioDTO              : "«create»"
DonacionesClient              -[#595959,dashed]->  DonacionAsignadaDTO          : "«create»"
Entrega                      "1" *-[#595959,plain]-> "destino\n1" BeneficiarioDTO              
Entrega                      "1" *-[#595959,plain]-> "camionAsignado\n1" Camion                       
Entrega                      "1" *-[#595959,plain]-> "donaciones\n*" DonacionAsignadaDTO          
Entrega                       -[#595959,dashed]->  EstadoEntrega                : "«create»"
Entrega                      "1" *-[#595959,plain]-> "historialEstados\n*" EstadoEntrega                
EntregaController            "1" *-[#595959,plain]-> "gestor\n1" GestorEntrega                
EntregaMapper                 -[#595959,dashed]->  EntregaResponse              : "«create»"
EntregaMapper                 -[#595959,dashed]->  EstadoEntregaDto             : "«create»"
EntregaRepository            "1" *-[#595959,plain]-> "store\n*" Entrega                      
EstacionRecepcion            "1" *-[#595959,plain]-> "repoCamiones\n1" CamionRepository             
EstacionRecepcion             -[#595959,dashed]->  Coordenada                   : "«create»"
EstacionRecepcion            "1" *-[#595959,plain]-> "repoGps\n1" GpsRepository                
EstadoEntrega                "1" *-[#595959,plain]-> "camion\n1" Camion                       
EstadoEntrega                "1" *-[#595959,plain]-> "tipoEstado\n1" TipoEstadoEntrega            
GestorEntrega                "1" *-[#595959,plain]-> "donacionesClient\n1" DonacionesClient             
GestorEntrega                "1" *-[#595959,plain]-> "entregaRepository\n1" EntregaRepository            
GestorRuta                   "1" *-[#595959,plain]-> "camionRepository\n1" CamionRepository             
GestorRuta                   "1" *-[#595959,plain]-> "donacionesClient\n1" DonacionesClient             
GestorRuta                   "1" *-[#595959,plain]-> "entregaRepository\n1" EntregaRepository            
GestorRuta                    -[#595959,dashed]->  OrquestadorLogistica         : "«create»"
GestorRuta                    -[#595959,dashed]->  ResultadoPlanificacion       : "«create»"
GestorRuta                   "1" *-[#595959,plain]-> "rutaRepository\n1" RutaRepository               
GpsRepository                "1" *-[#595959,plain]-> "gpsList\n*" Gps                          
LogisticaApp                  -[#595959,dashed]->  DonacionesClient             : "«create»"
LogisticaApp                  -[#595959,dashed]->  EntregaController            : "«create»"
LogisticaApp                  -[#595959,dashed]->  GestorEntrega                : "«create»"
LogisticaApp                  -[#595959,dashed]->  GestorRuta                   : "«create»"
LogisticaApp                  -[#595959,dashed]->  RutaController               : "«create»"
OrquestadorLogistica         "1" *-[#595959,plain]-> "camionesDisponibles\n*" Camion                       
OrquestadorLogistica         "1" *-[#595959,plain]-> "donacionesAllevar\n*" DonacionAsignadaDTO          
OrquestadorLogistica          -[#595959,dashed]->  Entrega                      : "«create»"
OrquestadorLogistica          -[#595959,dashed]->  Ruta                         : "«create»"
PruebaDonacionesClient        -[#595959,dashed]->  DonacionesClient             : "«create»"
PruebaRecepcion               -[#595959,dashed]->  Camion                       : "«create»"
PruebaRecepcion               -[#595959,dashed]->  EstacionRecepcion            : "«create»"
PruebaRecepcion               -[#595959,dashed]->  Gps                          : "«create»"
ResultadoPlanificacion       "1" *-[#595959,plain]-> "entregasPorCamion\n*" Camion                       
ResultadoPlanificacion       "1" *-[#595959,plain]-> "entregasSinAsignar\n*" Entrega                      
Ruta                         "1" *-[#595959,plain]-> "camion\n1" Camion                       
Ruta                         "1" *-[#595959,plain]-> "chofer\n1" Chofer                       
Ruta                         "1" *-[#595959,plain]-> "entregasOrdenadas\n*" Entrega                      
RutaController               "1" *-[#595959,plain]-> "gestor\n1" GestorRuta                   
RutaMapper                    -[#595959,dashed]->  RutaResponse                 : "«create»"
RutaRepository               "1" *-[#595959,plain]-> "store\n*" Ruta                         
@enduml
